# Generated by Django 6.0.3 on 2026-03-03 15:02

import netfields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', netfields.fields.InetAddressField(blank=True, max_length=39, null=True)),
                ('dj_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
    ]
