# Generated by Django 6.0.3 on 2026-03-05 15:08

import netfields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipv6field', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipmodel',
            name='ip_no_prefix',
            field=netfields.fields.InetAddressField(blank=True, max_length=39, null=True),
        ),
    ]
